# Generated by Django 2.2 on 2019-04-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_application_hosttoapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
